# Generated by Django 3.1 on 2020-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20201103_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(default='', max_length=512),
        ),
    ]
