# Generated by Django 3.1 on 2020-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20201103_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
