# Generated by Django 3.1 on 2020-11-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_hotel_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'room', 'checkin', 'checkout')},
        ),
    ]
