# Generated by Django 3.1 on 2020-11-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_auto_20201104_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
