# Generated by Django 3.1 on 2020-11-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_reservation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'hotel')},
        ),
    ]
